config/routes.rb
Brakkit::Application.routes.draw do

  resources :tournaments do
    member do
      post 'winner'
    end
    collection do
      post 'add_new_tournament'
      get 'search_tournaments'
    end

    resources :players do
      collection do
        post 'multiremove'
        post 'add_new_player'
      end
      member do
        delete 'delete_player_from_tournament_show'
      end
    end
  end

  resources :players do
    collection do
      post 'multiadd'
      post 'add_new_player'
      get 'search_players'
    end
    member do
      put 'update_player_ajax'
    end
  end

  resources :matches do
    collection do
      post 'add_new_match'
      get 'search_matches'
    end
    member do
      post 'verdict'
      post 'add_match_player'
      post 'remove_match_player'
      get 'non_match_players'
      post 'add_player_from_player_picker'
      get 'player_picker_search'
      post 'add_new_player_from_match'
    end

    resources :players do

    end
  end

  root to: 'tournaments#index'

  get '/home',    to: 'tournaments#index'
  get '/contact', to: 'static_pages#contact'
  get '/players', to: 'players#index'
  get '/players/:id', to: 'players#show'
  get '/tournaments/:id', to: 'tournaments#show'
  get '/tournaments/:id/player', to: 'players#show'
  get '/tournaments/:id/players/:id', to: 'players#show'
  post '/players/:id/edit', to: 'players#edit'
  post '/tournaments/:id/players/:id/edit', to: 'players#edit'
  get '/tournaments/:id/start', to: 'tournaments#start_tournament', as: 'start_tournament'
  get '/tournaments/:id/add_index/', to: 'players#add_index', as: 'add_index'
  get '/matches/:id/start_match', to: 'matches#start_match', as: 'start_match'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :name, :winner_id, :active, :winner_name

  validates :name, presence: true, uniqueness: true

  has_many :players, through: :tournament_players
  has_many :tournament_players, dependent: :destroy
  has_many :matches
  belongs_to :winner, class_name: Player, foreign_key: :winner_id


  before_save do |t|
    if winner_id != 0
      t.winner_name = Player.find(winner_id).full_name
    end
  end

  def setup_playoff

    if !self.matches.any? && self.players.any?
      self.active = true
      p = self.players
      p_length = p.length
      p.sort! { |a, b| a.skill <=> b.skill }
      round = 1
      playoff_matches = 0

      # Loop to see how many playoff matches there should be
      # This is equal to the number of players - the next lowest power of 2
      # Ex: 15 - 8 = 7 playoff matches

      while !power_of_2?(p_length)
        p_length = p_length - 1
        playoff_matches = playoff_matches + 1
      end

      # Initialize the head and tail to first two players
      # Give a temp variable so we can use playoff_matches later

      leftover = p.length - (playoff_matches * 2)
      true_length = p.length - playoff_matches
      iterations = Math.log2(true_length) - 2
      filler_matches = true_length - playoff_matches
      p_tail = 1
      p_head = 0
      counter = playoff_matches
      move_length = true_length/4
      pma = [] # Playoff matches array
      pma_index = true_length - 1
      switch = false

      # Set up the playoff round
      
      while counter > 0
        first_player = p[p_tail]
        second_player = p[p_head]

        if counter == playoff_matches
          pma << Match.new({round: round, tournament_id: self.id, name: ""})
          pma << Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
        elsif switch == true
          pma[pma_index] = Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
          if pma_index == 3
            pma_index = 2
          elsif pma_index == 2
            pma_index = true_length - 4
            move_length = 4
            switch = false
          elsif pma_index + move_length >= true_length
            iterations = iterations - 1
            if iterations == 0
              pma_index = 3
            else
              pma_index = pma_index + 2
              move_length = 4
              switch = false
            end
          else
            pma_index = pma_index + move_length
            if iterations > 0
              move_length = true_length/4
            elsif iterations < 0
              move_length = 4
            end
          end
        else
          pma[pma_index] = Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
          if pma_index - move_length <= 3 || pma[pma_index - move_length] != nil
            switch = true
            iterations = iterations - 1
            if iterations == 0
              pma_index = 3
            elsif iterations < 0
              move_length = move_length/2
              pma_index = pma_index + move_length
              move_length = 4
            else
              pma_index = pma_index - 2
              move_length = 2 * (Math.log2(true_length) - 2)
            end
          else
            pma_index = pma_index - move_length
          end
        end

        if p_head == 0
          p_tail = (playoff_matches * 2) - 1
          p_head = p_head + 2
        else
          p_tail = p_tail - 1
          p_head = p_head + 1
        end

        counter = counter - 1

      end

      # If only one playoff match, create space for the filler matches to be placed later

      if playoff_matches == 1 && p.length > 3
        pma[filler_matches] = nil
      end

      # Reverse the order of the weaker playoff matches past the first if more than 2
      # This way, the seeding for playoff matches is lined up correctly with non-playoff matches

      if playoff_matches > 2
        check_front = 3
        check_end = true_length - 1
        while check_front < check_end
          if pma[check_front] != nil && pma[check_end] != nil
            temp = pma[check_front]
            pma[check_front] = pma[check_end]
            pma[check_end] = temp
            check_front = check_front + 2
            check_end = check_end - 2
          else
            check_front = check_front + 2
          end
        end
      end

      # Replace all nils in the array with blank matches

      # m = Match.create({round: round, tournament_id: self.id, name: ""})
      # pma.map! { |x| x == nil ? m : x }

      # Assign the playoff matches array's content to our tournament

      while pma.length > 0
        if pma[0] == nil
          self.matches << Match.new({round: round, tournament_id: self.id, name: ""})
          pma.delete_at(0)
        else
          self.matches << pma.shift
        end
      end

      # Set up the other rounds

      round = round + 1
      if p.length > (true_length + true_length/2)
        spare_players = true_length - (p.length - true_length)
      else
        spare_players = p.length - true_length
      end
      rounds = Math.log2(true_length) + 1
      match_count = (true_length) / 2
      p_tail = p.length - 1
      p_head = p.length - leftover
      match_array = []

      # Iterate through the rest of the players left in the players array and add them according to skill

      while round <= rounds
        temp = match_count
        while temp > 0
          if p_head == p_tail || spare_players > 0
            first_player = p[p_tail]
            match_array << Match.new({player1_id: first_player.id, round: round, tournament_id: self.id, name: ""})
            p_tail = p_tail - 1
          elsif p_head < p_tail
            first_player = p[p_tail]
            second_player = p[p_head]
            match_array << Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
            p_tail = p_tail - 1
            p_head = p_head + 1
          else
            m = Match.new({round: round, tournament_id: self.id, name: ""})
            if round > 2
              self.matches << m
            else
              match_array << m
            end
          end
          temp = temp - 1
          spare_players = spare_players - 1
        end

        # Logic for seeding the non-playoff players

        if round == 2
          head = 0
          tail = match_array.length - 1
          counter = 1

          if head == tail
            self.matches << match_array[head]
          else
            while counter <= (match_array.length / 2)
              self.matches << match_array[head]
              self.matches << match_array[tail]
              if counter == 1
                head = (tail / 2) + 1
                tail = head - 1
              else
                head = head + 1
                tail = tail - 1
              end
              counter = counter + 1
            end
          end
        end

        round = round + 1
        match_count = match_count / 2
      end

      self.matches.each { |m|
        m.save
      }

      self.save

    end

  end

  def setup_normal
    if !self.matches.any? && self.players.any?

      players = self.players
      players_length = players.length
      self.active = true
      players.sort! { |a, b| a.skill <=> b.skill }
      round = 1
      rounds = Math.log2(players_length)
      match_count = 0
      match_array = []

      i = 0
      j = players_length - 1

      # round 1 loop

      temp = players_length / 2

      while temp > 0
        first_player = players[j]
        second_player = players[i]

        m = Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id})
        match_array << m
        match_count = match_count + 1
        temp = temp - 1
        i = i + 1
        j = j - 1
      end

      head = 0
      tail = match_array.length - 1
      counter = 1

      if head == tail
        self.matches << match_array[head]
      else
        while counter <= (match_array.length / 2)
          self.matches << match_array[head]
          self.matches << match_array[tail]
          if counter == 1
            head = (tail / 2) + 1
            tail = head - 1
          else
            head = head + 1
            tail = tail - 1
          end
          counter = counter + 1
        end
      end

      round = round + 1
      bro = match_count / 2

      while round <= rounds
        temp = bro
        while temp > 0
          m = Match.new({round: round, tournament_id: self.id})
          self.matches << m
          match_count = match_count + 1
          temp = temp - 1
        end
        round = round + 1
        bro = bro / 2
      end

      self.matches.each { |m|
        m.save
      }

      self.save

    end
  end

  def start_tournament
    if power_of_2?(self.players.length)
      setup_normal
    else
      setup_playoff
    end

  end

  def power_of_2?(number)
    return true if number == 1
    return false if number == 0 || number % 2 != 0
    power_of_2?(number / 2)
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController

  def new
    @tournament = Tournament.new

    add_breadcrumb "Tournaments", :tournaments_path
    add_breadcrumb "<span>New Tournament</span>", new_tournament_path
  end

  def index
    @tournament = Tournament.new
    @tournaments = Tournament.order("created_at DESC").paginate(page: params[:page], per_page: 10)
    @winner = @tournament.winner if @tournament.winner_id != 0
  end

  def show
    @tournament = Tournament.find(params[:id])
    @player = Player.new

    add_breadcrumb "Tournaments", :tournaments_path
    add_breadcrumb "<span>#{@tournament.name}</span>", tournament_path(@tournament)
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def create
    @tournament = Tournament.new(params[:tournament])

    respond_to do |format|
      if @tournament.save
        format.html {
          flash[:success] = "Tournament created!"
          redirect_to @tournament
        }
        format.js
      else
        format.html {
          render 'new'
        }
        format.js
      end
    end

  end

  def start_tournament

    @tournament = Tournament.find(params[:id])
    @tournament.start_tournament
    @matches = @tournament.matches

    add_breadcrumb "Tournaments", :tournaments_path
    add_breadcrumb "#{@tournament.name}", tournament_path(@tournament)
    add_breadcrumb "<span>Bracket View</span>", start_tournament_path

  end

  def destroy

    Tournament.find(params[:id]).destroy
    flash[:success] = "Tournament deleted!"
    redirect_to tournaments_path

  end

  def winner
    @tournament = Tournament.find(params[:id])
    @match = Match.find(params['match-id'])
    @player = Player.find(params['player-id'])
    match_number = params['match-number'].to_i
    round = params['round-id'].to_i

    if(@match.player1_id == @player.id)
      @loser = @match.player2
    else
      @loser = @match.player1
    end

    loser_name = "#{@loser.first_name} #{@loser.last_name}"

    if(match_number % 2 == 0)
      next_match = match_number / 2
    else
      next_match = (match_number + 1) / 2
    end

    if @tournament.matches.where(round: round + 1).any?
      next_match_number = next_match + (@tournament.matches.where(round: 1).count)
      next_match_id = next_match_number + @tournament.matches.first.id - 1
    else
      next_match_id = 0
    end


    @match.winner_id = @player.id
    @player.increment_wins
    winner_name = "#{@player.first_name}" + " " + "#{@player.last_name}"
    @player.save
    @match.save

    if next_match_id != 0

      @next_match = Match.find(next_match_id)

      if(@next_match.player1_id == 0)
        @next_match.player1_id = @player.id
        next_match_player = 1
      else
        @next_match.player2_id = @player.id
        next_match_player = 2
      end

      @next_match.save

    else
      @tournament.winner_id = @player.id
      @tournament.winner_name = @player.full_name
      @tournament.active = false
      @tournament.save
    end

    respond_to do |format|
      format.json {
        render json: {
            player: @player,
            match: @match,
            tournament_id: @tournament.id,
            winner_name: winner_name,
            loser_name: loser_name,
            next_match_id: next_match_id,
            next_match_player: next_match_player,
            next_match_number: next_match_number
        }
      }

    end
  end

  def add_new_tournament

    @tournament = Tournament.new(name: params['name'])

    respond_to do |format|
      format.json {
        if @tournament.save
          render json: {
              tournament: @tournament,
          }
        else
          render json: @tournament.errors, status: :forbidden
        end

      }

    end
  end

  def search_tournaments

    search = params['search_term']

    if !search.empty?
      search_result = Tournament.where("name LIKE :test OR winner_name LIKE :test", test: "%#{search}%").uniq.reverse
      search = search.to_i
      search_result = search_result + Tournament.includes(:players).group('tournaments.id').having('count(players.id)=(?)', search).paginate(page: params[:page], per_page: 10)
      if search != 0
        search_result.reverse!
      end
    else
      search_result = Tournament.order("created_at DESC").paginate(page: params[:page], per_page: 10)
    end

    search_result = search_result.map do |s|
      if s.winner_id == 0
        if s.active
          status = "Active"
        else
          status = "Inactive"
        end
        winner_name = ""
      else
        status = "Completed"
        winner_name = s.winner_name
      end
      {
          id: s.id,
          name: s.name,
          status: status,
          player_count: s.players.count,
          winner_name: winner_name,
          winner_id: s.winner_id
      }
    end

    respond_to do |format|
      format.json {
        render json: {
            search_result: search_result
        }
      }
    end
  end

  def update
    t = Tournament.find(params['tournament_id'])
    t.name = params['name']

    respond_to do |format|
      format.json {
        if t.save
          render json: {
              new_name: t.name
          }
        else
          render json: t.errors, status: :forbidden
        end
      }
    end
  end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_edit_tournament_name.html.erb
<div class="edit_tournament_name_class">
    <%= form_for @tournament, html: { id: 'edit_tournament_name_form', class: 'nopjax' } do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <ul>
            <li class="tournament_name_text_field"><%= f.text_field :name, autofocus: true, placeholder: "New Tournament Name" %></li>
        </ul>
    <% end %>
</div>

app/views/tournaments/_new_tournament.html.erb
<div class="create_form">
    <%= form_for @tournament, html: { id: 'tournament-dialog-form', class: 'nopjax' } do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <ul>
        	<li><%= f.text_field :name, autofocus: true, placeholder: "Tournament Name" %></li>
            <li><%= f.submit "Create Tournament" %></li>
            <li class="cancel_btn" id="tournament_cancel_btn"><%= button_tag "Cancel", class: "edit_btn" %></li>
        </ul>
    <% end %>
</div>

app/views/tournaments/_tournaments_table.html.erb
<%= will_paginate @tournaments %>

<table>
    <thead>
    <tr>
        <th>Tournament Name</th>
        <th># of Players</th>
        <th>Status</th>
        <th>Winner</th>
    </tr>
    </thead>
        <tbody id="tournaments_table">
        <% if @tournaments.any? %>
            <% @tournaments.each do |t| %>
                <tr data-tournament-id="<%= t.id %>">
                    <td><%= link_to t.name, tournament_path(t) %></td>
                    <td><%= t.players.count %></td>
                    <td>
                        <% if @winner %>
                            Completed
                        <% else %>
                            <%= t.active ? "Active" : "Inactive"  %>
                        <% end %>
                    </td>
                    <td>
                        <% if @winner %>
                            <%= link_to "#{@winner.full_name}", player_path(@winner) %>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
</table>

app/views/tournaments/index.html.erb
<h2 class="title">Tournaments</h2>
<div class='btn create_btn' id='new_tournament_btn'><%= link_to "New Tournament", new_tournament_url, class: 'nopjax' %></div>

<%= render 'new_tournament' %>

<div class="detail">
    <%= pluralize(Tournament.count, 'tournament has', 'tournaments have') %> been created so far.
</div>
<div class="divider"></div>

<div class="search_box">
	<input type="text" id="tournament_search" placeholder="Search for tournament..." class="search">
</div>

<%= render 'tournaments_table' %>

app/views/tournaments/new.html.erb
<%= render 'layouts/breadcrumbs' %>
<div>
	<h2 class="title">New Tournament</h2>
</div>
<div class="detail">Please enter a name for the new tournament.</div>
<div class="divider"></div>
<div class="create_form_tournament show_form">
	<%= form_for @tournament, html: { id: 'tournament-dialog-form' } do |f| %>
	    <%= render 'shared/error_messages', object: f.object %>
	    <ul>
		    <li><span>Tournament Name</span></li>
		    <li><%= f.text_field :name, autofocus: true %></li>
		    <li><%= f.submit "Create Tournament" %></li>
		</ul>
	<% end %>
</div>

app/views/tournaments/show.html.erb
<%= flash[:notice] %>

<%= render 'layouts/breadcrumbs' %>

<div><h2 class="title"><%= @tournament.name %></h2></div>

<% if @tournament.winner_id == 0 %>
    <div class="btn start_btn">
        <% if !@tournament.active %>
            <%= link_to "Start Tournament", start_tournament_path(@tournament), class: 'nopjax', confirm: "WARNING: Once the tournament is started, you cannot add or remove players." %>
        <% else %>
            <%= link_to "Resume Tournament",  start_tournament_path(@tournament), class: 'nopjax' %>
        <% end %>
    </div>

<% else %>
    <div class="btn completed_btn"><%= link_to "Tournament Completed" %></div>
<% end %>
<div class="btn delete_btn"><%= link_to "Delete Tournament", @tournament, confirm: "Did you really mean to delete this tournament?", method: :delete %></div>

<div class="btn edit_btn" id="edit_tournament_name_button" data-tournament-id="<%= @tournament.id %>"><%= link_to "Edit Tournament Name" %></div>

<ul class="detail">
    <li><%= @tournament.active ? "Active" : "Inactive"  %></li>
    <li><%= pluralize(@tournament.players.count, "player") %></li>
    <li>
        <% temp_id = @tournament.winner_id %>
        <% if temp_id != 0 %>
            <% p = Player.find(temp_id) %>
                Winner: <%= p.first_name %> <%= p.last_name %>
        <% end %>
    </li>
</ul>
<div class="divider"></div>



    <h3 class="subtitle">Players</h3>

    <% if !@tournament.active? %>
    <div class="btn" id="add_tournament_player_button" data-tournament-id="<%= params[:id] %>"> <%= link_to "Add New Player", new_tournament_player_path(@tournament) %></div>
    <div class="btn"> <%= link_to "Add Existing Players", add_index_path(@tournament), class: "nopjax" %></div>
    <% end %>

    <%= form_tag multiremove_tournament_players_path(@tournament) do %>

    <% if !@tournament.active? %>
    <% if @tournament.players.any? %>
        <%= submit_tag "Remove Checked", class: "submit_btn remove" %>
    <% end %>
    <% end %>

    <table>
        <thead>
            <tr>
                <th>
                    <% if !@tournament.active? %>
                    <input type="checkbox" id="checkall" />
                    <% end %>
                </th>
                <th>Name</th>
                <th>Email</th>
                <th>Skill Level</th>
                <th>Matches Won</th>
            </tr>
        </thead>
        <tbody>
            <% if @tournament.players.any? %>
                <% @tournament.players.order("created_at DESC").each do |p| %>
                <tr>
                    <% temp = "#{p.first_name} #{p.last_name}" %>
                    <td>
                        <% if !@tournament.active? %>
                        <%= check_box_tag "player_ids[]", p.id %>
                        <% end %>
                    </td>
                    <td><%= link_to "#{temp}", tournament_player_path(@tournament, p) %></td>
                    <td><%= p.email %></td>
                    <td><%= p.skill %></td>
                    <td><%= p.matches_won %></td>
                </tr>
                <% end %>
            <% end %>
        </tbody>
    </table>

    <%= hidden_field_tag "tournament_id", @tournament.id %>
    <% end %>


<%= render 'layouts/new_player' %>

<%= render 'edit_tournament_name' %>

app/views/tournaments/start_tournament.html.erb
<div class="round_container">

    <%= render 'layouts/breadcrumbs' %>

    <div>
        <h2 class="title"><%= @tournament.name %></h2>
    </div>

    <ul class="detail">
        <li><%= pluralize(@tournament.players.count, "player") %></li>
        <li id="tournament-winner">
            <% temp_id = @tournament.winner_id %>
            <% if temp_id != 0 %>
                <% p = @tournament.winner %>
                Winner: <%= link_to p.full_name, player_path(p) %>
            <% else %>
                There is no winner yet.
            <% end %>
        </li>
    </ul>

    <div class="divider"></div>

    <% match_number = 1 %>
    <% cur_round = 0 %>

    <% @matches.each do |m| %>
        <% if cur_round != m.round %>
            <% cur_round = m.round %>
            <% if cur_round != 1 %>
                </div>
            <% end %>
                <div class="round round-<%= cur_round %>">
        <% end %>

        <% non_match = (cur_round == 1 && m.player1_id == 0 && m.player2_id == 0) %>

        <div class="matches-row <%= "non-match-row" if non_match %>">

            <ul class="matches-list">
                <div id="match-<%= m.id %>" class="match <%= "non-match" if non_match %>">

                    <% winner_id = m.winner_id %>

                    <% p1 = m.player1 if m.player1_id != 0 %>
                    <% p2 = m.player2 if m.player2_id != 0 %>

                    <% p1_is_winner = false %>
                    <% p2_is_winner = false %>

                    <% if p1 && p2 && winner_id != 0 %>
                        <% winner_id == p1.id ? p1_is_winner = true : p2_is_winner = true %>

                    <% end %>

                        <li class="<% if winner_id != 0 %>
                                            <%= p1_is_winner ? "match-winner" : "match-loser" %>
                                         <% end %>">
                        <% if winner_id != 0 %>
                            <%= gravatar_for p1, size: 30 %>
                            <%= p1 ? "#{p1.first_name} #{p1.last_name}" : ""  %>
                        <% elsif p1 %>
                            <button class="winner_btn tournament_match_winner_btn" data-match-id="<%= m.id %>" data-player-id="<%= p1.id if p1%>" data-round-id="<%= m.round %>"
                                    data-match-number="<%= match_number %>" data-player-number="1"><%= gravatar_for p1, size: 30 %><%= p1 ? "#{p1.first_name} #{p1.last_name}" : "" %>
                            </button>
                        <% end %>
                        </li>

                        <li class="<% if winner_id != 0 %>
                                             <%= p2_is_winner ? "match-winner" : "match-loser" %>
                                         <% end %>">
                            <% if winner_id != 0 %>
                            <%= gravatar_for p2, size: 30 %>
                            <%= p2 ? "#{p2.first_name} #{p2.last_name}" : ""  %>
                        <% elsif p2 %>
                            <button class="winner_btn tournament_match_winner_btn" data-match-id="<%= m.id %>" data-player-id="<%= p2.id if p2%>" data-round-id="<%= m.round %>"
                                    data-match-number="<%= match_number %>" data-player-number="2"><%= gravatar_for p2, size: 30 %><%= p2 ? "#{p2.first_name} #{p2.last_name}" : ""  %>
                            </button>
                        <% end %>
                        </li>
                    <% match_number = match_number + 1 %>

                </div>
            </ul>

            <div class="match-border-filler"></div>
            <div class="match-border"></div>
        </div>

    <% end %>

    </div>

</div>

<div id="filler"></div>