config/routes.rb
Brakkit::Application.routes.draw do

  resources :tournaments do
    member do
      post 'winner'
    end
    collection do
      post 'add_new_tournament'
      get 'search_tournaments'
    end

    resources :players do
      collection do
        post 'multiremove'
        post 'add_new_player'
      end
      member do
        delete 'delete_player_from_tournament_show'
      end
    end
  end

  resources :players do
    collection do
      post 'multiadd'
      post 'add_new_player'
      get 'search_players'
    end
    member do
      put 'update_player_ajax'
    end
  end

  resources :matches do
    collection do
      post 'add_new_match'
      get 'search_matches'
    end
    member do
      post 'verdict'
      post 'add_match_player'
      post 'remove_match_player'
      get 'non_match_players'
      post 'add_player_from_player_picker'
      get 'player_picker_search'
      post 'add_new_player_from_match'
    end

    resources :players do

    end
  end

  root to: 'tournaments#index'

  get '/home',    to: 'tournaments#index'
  get '/contact', to: 'static_pages#contact'
  get '/players', to: 'players#index'
  get '/players/:id', to: 'players#show'
  get '/tournaments/:id', to: 'tournaments#show'
  get '/tournaments/:id/player', to: 'players#show'
  get '/tournaments/:id/players/:id', to: 'players#show'
  post '/players/:id/edit', to: 'players#edit'
  post '/tournaments/:id/players/:id/edit', to: 'players#edit'
  get '/tournaments/:id/start', to: 'tournaments#start_tournament', as: 'start_tournament'
  get '/tournaments/:id/add_index/', to: 'players#add_index', as: 'add_index'
  get '/matches/:id/start_match', to: 'matches#start_match', as: 'start_match'

end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :skill, :matches_won, :full_name

  before_save do |user|
    user.email = email.downcase
    user.full_name = "#{first_name} #{last_name}"
  end

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :full_name, uniqueness: true
  validates :skill, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_many :tournaments, through: :tournament_players
  has_many :tournament_players, dependent: :destroy
  belongs_to :match

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def increment_wins
    self.matches_won = self.matches_won + 1
    self.save(validate: false)
  end

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  attr_accessible :name, :winner_id, :active, :winner_name

  validates :name, presence: true, uniqueness: true

  has_many :players, through: :tournament_players
  has_many :tournament_players, dependent: :destroy
  has_many :matches
  belongs_to :winner, class_name: Player, foreign_key: :winner_id


  before_save do |t|
    if winner_id != 0
      t.winner_name = Player.find(winner_id).full_name
    end
  end

  def setup_playoff

    if !self.matches.any? && self.players.any?
      self.active = true
      p = self.players
      p_length = p.length
      p.sort! { |a, b| a.skill <=> b.skill }
      round = 1
      playoff_matches = 0

      # Loop to see how many playoff matches there should be
      # This is equal to the number of players - the next lowest power of 2
      # Ex: 15 - 8 = 7 playoff matches

      while !power_of_2?(p_length)
        p_length = p_length - 1
        playoff_matches = playoff_matches + 1
      end

      # Initialize the head and tail to first two players
      # Give a temp variable so we can use playoff_matches later

      leftover = p.length - (playoff_matches * 2)
      true_length = p.length - playoff_matches
      iterations = Math.log2(true_length) - 2
      filler_matches = true_length - playoff_matches
      p_tail = 1
      p_head = 0
      counter = playoff_matches
      move_length = true_length/4
      pma = [] # Playoff matches array
      pma_index = true_length - 1
      switch = false

      # Set up the playoff round
      
      while counter > 0
        first_player = p[p_tail]
        second_player = p[p_head]

        if counter == playoff_matches
          pma << Match.new({round: round, tournament_id: self.id, name: ""})
          pma << Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
        elsif switch == true
          pma[pma_index] = Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
          if pma_index == 3
            pma_index = 2
          elsif pma_index == 2
            pma_index = true_length - 4
            move_length = 4
            switch = false
          elsif pma_index + move_length >= true_length
            iterations = iterations - 1
            if iterations == 0
              pma_index = 3
            else
              pma_index = pma_index + 2
              move_length = 4
              switch = false
            end
          else
            pma_index = pma_index + move_length
            if iterations > 0
              move_length = true_length/4
            elsif iterations < 0
              move_length = 4
            end
          end
        else
          pma[pma_index] = Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
          if pma_index - move_length <= 3 || pma[pma_index - move_length] != nil
            switch = true
            iterations = iterations - 1
            if iterations == 0
              pma_index = 3
            elsif iterations < 0
              move_length = move_length/2
              pma_index = pma_index + move_length
              move_length = 4
            else
              pma_index = pma_index - 2
              move_length = 2 * (Math.log2(true_length) - 2)
            end
          else
            pma_index = pma_index - move_length
          end
        end

        if p_head == 0
          p_tail = (playoff_matches * 2) - 1
          p_head = p_head + 2
        else
          p_tail = p_tail - 1
          p_head = p_head + 1
        end

        counter = counter - 1

      end

      # If only one playoff match, create space for the filler matches to be placed later

      if playoff_matches == 1 && p.length > 3
        pma[filler_matches] = nil
      end

      # Reverse the order of the weaker playoff matches past the first if more than 2
      # This way, the seeding for playoff matches is lined up correctly with non-playoff matches

      if playoff_matches > 2
        check_front = 3
        check_end = true_length - 1
        while check_front < check_end
          if pma[check_front] != nil && pma[check_end] != nil
            temp = pma[check_front]
            pma[check_front] = pma[check_end]
            pma[check_end] = temp
            check_front = check_front + 2
            check_end = check_end - 2
          else
            check_front = check_front + 2
          end
        end
      end

      # Replace all nils in the array with blank matches

      # m = Match.create({round: round, tournament_id: self.id, name: ""})
      # pma.map! { |x| x == nil ? m : x }

      # Assign the playoff matches array's content to our tournament

      while pma.length > 0
        if pma[0] == nil
          self.matches << Match.new({round: round, tournament_id: self.id, name: ""})
          pma.delete_at(0)
        else
          self.matches << pma.shift
        end
      end

      # Set up the other rounds

      round = round + 1
      if p.length > (true_length + true_length/2)
        spare_players = true_length - (p.length - true_length)
      else
        spare_players = p.length - true_length
      end
      rounds = Math.log2(true_length) + 1
      match_count = (true_length) / 2
      p_tail = p.length - 1
      p_head = p.length - leftover
      match_array = []

      # Iterate through the rest of the players left in the players array and add them according to skill

      while round <= rounds
        temp = match_count
        while temp > 0
          if p_head == p_tail || spare_players > 0
            first_player = p[p_tail]
            match_array << Match.new({player1_id: first_player.id, round: round, tournament_id: self.id, name: ""})
            p_tail = p_tail - 1
          elsif p_head < p_tail
            first_player = p[p_tail]
            second_player = p[p_head]
            match_array << Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id, name: ""})
            p_tail = p_tail - 1
            p_head = p_head + 1
          else
            m = Match.new({round: round, tournament_id: self.id, name: ""})
            if round > 2
              self.matches << m
            else
              match_array << m
            end
          end
          temp = temp - 1
          spare_players = spare_players - 1
        end

        # Logic for seeding the non-playoff players

        if round == 2
          head = 0
          tail = match_array.length - 1
          counter = 1

          if head == tail
            self.matches << match_array[head]
          else
            while counter <= (match_array.length / 2)
              self.matches << match_array[head]
              self.matches << match_array[tail]
              if counter == 1
                head = (tail / 2) + 1
                tail = head - 1
              else
                head = head + 1
                tail = tail - 1
              end
              counter = counter + 1
            end
          end
        end

        round = round + 1
        match_count = match_count / 2
      end

      self.matches.each { |m|
        m.save
      }

      self.save

    end

  end

  def setup_normal
    if !self.matches.any? && self.players.any?

      players = self.players
      players_length = players.length
      self.active = true
      players.sort! { |a, b| a.skill <=> b.skill }
      round = 1
      rounds = Math.log2(players_length)
      match_count = 0
      match_array = []

      i = 0
      j = players_length - 1

      # round 1 loop

      temp = players_length / 2

      while temp > 0
        first_player = players[j]
        second_player = players[i]

        m = Match.new({player1_id: first_player.id, player2_id: second_player.id, round: round, tournament_id: self.id})
        match_array << m
        match_count = match_count + 1
        temp = temp - 1
        i = i + 1
        j = j - 1
      end

      head = 0
      tail = match_array.length - 1
      counter = 1

      if head == tail
        self.matches << match_array[head]
      else
        while counter <= (match_array.length / 2)
          self.matches << match_array[head]
          self.matches << match_array[tail]
          if counter == 1
            head = (tail / 2) + 1
            tail = head - 1
          else
            head = head + 1
            tail = tail - 1
          end
          counter = counter + 1
        end
      end

      round = round + 1
      bro = match_count / 2

      while round <= rounds
        temp = bro
        while temp > 0
          m = Match.new({round: round, tournament_id: self.id})
          self.matches << m
          match_count = match_count + 1
          temp = temp - 1
        end
        round = round + 1
        bro = bro / 2
      end

      self.matches.each { |m|
        m.save
      }

      self.save

    end
  end

  def start_tournament
    if power_of_2?(self.players.length)
      setup_normal
    else
      setup_playoff
    end

  end

  def power_of_2?(number)
    return true if number == 1
    return false if number == 0 || number % 2 != 0
    power_of_2?(number / 2)
  end

end

app/helpers/players_helper.rb
module PlayersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(player, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(player.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: player.first_name + player.last_name, class: "gravatar")
	end

end

app/views/players/_player_matches.html.erb
<h3 class="subtitle">Matches</h3>

<%= will_paginate @matches, param_name: 'matches_page' %>

<table>
    <thead>
    <tr>
        <th>Match</th>
        <th>Other Player</th>
        <th>Winner</th>
    </tr>
    </thead>
        <tbody>
        <% if @matches.any? %>
            <% @matches.each do |m| %>
                <tr>
                    <td><%= link_to m.id, match_path(m) %></td>
                    <td><% if m.player1_id == @player.id  %>
                            <%= link_to m.player2.full_name, player_path(m.player2) if m.player2 %>
                        <% else %>
                            <%= link_to m.player1.full_name, player_path(m.player1) if m.player1 %>
                        <% end %></td>
                    <td><%= link_to m.winner.full_name, player_path(m.winner) if m.winner %></td>


                </tr>
            <% end %>
        <% end %>
        </tbody>
</table>

app/views/players/_player_tournaments.html.erb
<h3 class="subtitle">Tournaments</h3>

<%= will_paginate @player_tournaments, param_name: 'tournaments_page' %>

<table>
    <thead>
    <tr>
        <th>Tournament Name</th>
        <th># of Players</th>
        <th>Status</th>
        <th>Winner</th>
    </tr>
    </thead>
    <% if @player_tournaments.any? %>
        <tbody>
        <% @player_tournaments.each do |t| %>
            <tr>
                <td><%= link_to t.name, tournament_path(t) %></td>
                <td><%= t.players.count %></td>
                <% temp_id = t.winner_id %>
                <td>
                    <% if temp_id != 0 %>
                        Completed
                    <% else %>
                        <%= t.active ? "Active" : "Inactive"  %>
                    <% end %>
                </td>
                <td>
                    <% if temp_id != 0 %>
                        <% p = Player.find(temp_id) %>
                        <% temp = "#{p.first_name} #{p.last_name}" %>
                        <%= link_to "#{temp}", player_path(p) %>
                    <% end %>
                </td>
            </tr>
        <% end %>
        </tbody>
    <% end %>
</table>

app/views/players/_reg_index.html.erb
<div id="players_pagination">
    <%= will_paginate @players %>
</div>

<table>
    <thead>
    	<tr>
    		<th>Name</th>
    		<th>Email</th>
    		<th>Skill</th>
    		<th>Matches Won</th>
    	</tr>
    </thead>
    <% if @players.any? %>
    <tbody id="players_table">
    	<% @players.each do |p| %>
        <tr>
        	<% temp = "#{p.first_name} #{p.last_name}" %>
            <td><%= link_to "#{temp}", player_path(p) %></td>
            <td><%= p.email %></td>
            <td><%= p.skill %></td>
            <td><%= p.matches_won %></td>
        </tr>
	    <% end %>
    </tbody>
    <% end %>
</table>

app/views/players/add_index.html.erb
<%= render 'layouts/breadcrumbs' %>

<div>
    <h2 class="title">Add Existing Players</h2>
</div>

<div class="detail">
    <h4><%= "#{@tournament.name}"%></h4>
    <p><%= pluralize(@players.count, 'player has', 'players have') %> not been added to this tournament yet.</p>
</div>
<div class="divider"></div>

<%= will_paginate @players %>

<%= form_tag multiadd_players_path do %>

<%= submit_tag "Add Checked", class: "submit_btn add_existing" %>

<table>
    <thead>
    	<tr>
            <th><input type="checkbox" id="checkall" /></th>
    		<th>Name</th>
    		<th>Email</th>
    		<th>Skill</th>
    		<th>Matches Won</th>
    	</tr>
    </thead>
    <% if @players.any? %>
    <tbody>
    	<% @players.order("created_at DESC").each do |p| %>
        
        <tr>
        	<% temp = "#{p.first_name} #{p.last_name}" %>
            <td><%= check_box_tag "player_ids[]", p.id %></td>
            <td><%= link_to "#{temp}", player_path(p) %></td>
            <td><%= p.email %></td>
            <td><%= p.skill %></td>
            <td><%= p.matches_won %></td>
        </tr>
        
	    <% end %>
    </tbody>
    <% end %>
</table>
<%= hidden_field_tag "tournament_id", @tournament.id %>
<% end %>

app/views/players/edit.html.erb
<%= render 'layouts/breadcrumbs' %>

<div>
    <h2 class="title">Edit <%= @player.full_name %></h2>
</div>
<div class="divider"></div>

<div class="create_form_player edit_player">
    <%= form_for @player do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <ul>
            <li><%= gravatar_for @player, size: 93 %></li>
            <li><a href="http://gravatar.com/emails">Change Gravatar</a></li>
            <li><span>First Name</span></li>
            <li><%= f.text_field :first_name, autofocus: true %></li>
            <li><span>Last Name</span></li>
            <li><%= f.text_field :last_name %></li>
            <li><span>Email Address</span></li>
            <li><%= f.email_field :email %></li>
            <li><span>Skill Level</span></li>
            <li><%= f.select :skill, 1..10 %></li>
            <% if @tournament %>
                <%= f.hidden_field :tournament_id, value: @tournament.id %>
            <% end %>
            <% if @match %>
                <%= f.hidden_field :match_id, value: @match.id %>
            <% end %>
            <li><%= f.submit "Save Changes" %></li>
        </ul>
    <% end %>
</div>

app/views/players/index.html.erb
<h2 class="title">Players</h2>
<div class='btn create_btn nopjax' id='new_player_btn'><%= link_to "New Player", new_match_path %></div>

<%= render 'layouts/new_player' %>

<div class="detail">
	<%= pluralize(Player.count, 'player has', 'players have') %> been created so far.
</div>
<div class="divider"></div>

<div class="search_box">
	<input type="text" id="player_search" placeholder="Search for player..." class="search">
</div>

<%= render 'reg_index' %>

app/views/players/new.html.erb
<%= render 'layouts/breadcrumbs' %>

<div><h2 class="title">New Player</h2></div>
<div class="detail">Please enter details for the new player.</div>
<div class="divider"></div>
<div class="create_form_tournament show_form">
	<%= form_for @player, html: { id: 'player-dialog-form' } do |f| %>
	    <%= render 'shared/error_messages', object: f.object %>

        <ul>
		    <li><span>First Name</span></li>
		    <li><%= f.text_field :first_name, autofocus: true %></li>
		    <li><span>Last Name</span></li>
		    <li><%= f.text_field :last_name %></li>
		    <li><span>Email Address</span></li>
		    <li><%= f.email_field :email %></li>
		    <li><span>Skill Level</span></li>
		    <li><%= f.select :skill, 1..10 %></li>

            <li><%= f.submit "Create Player" %></li>
            <% if @tournament %>
                <%= f.hidden_field :tournament_id, value: @tournament.id %>
            <% end %>

		</ul>
	<% end %>
</div>

app/views/players/show.html.erb
<%= render 'layouts/breadcrumbs' %>

<div class="player-info">
    <%= gravatar_for @player, size: 93 %>
    <div class="detail">
        <h2 class="title">
            <%= "#{@player.first_name} #{@player.last_name}" %>
        </h2>
        <ul>
            <li><%= @player.email %></li>
            <li>Skill: <%= @player.skill %></li>
            <li>Matches Won: <%= @player.matches_won %></li>
        </ul>
    </div>
</div>
<% if @tournament %>
    <div class="btn remove_btn"><%= link_to "Remove Player from #{@tournament.name}", tournament_player_path(@tournament, @player), method: :delete %></div>
<% end %>

<div class="btn edit_btn" id="edit_player_btn" data-player-id="<%= @player.id %>" <% if @tournament %>
    data-tournament-id="<%= @tournament.id %>"
    <% elsif @match %>
            data-match-id="<%= @match.id %>"
    <% end %>>
    <%= link_to "Edit Player", if @tournament
                                 edit_tournament_player_path(@tournament, @player )
                                elsif @match
                                 edit_match_player_path(@match, @player)
                                 else
                                 edit_player_path(@player)
                                 end %></div>
<div class="btn delete_btn"><%= link_to "Delete Player", if @tournament
                                                           delete_player_from_tournament_show_tournament_player_path(@tournament, @player)
                                                         elsif @match
                                                           match_player_path(@match, @player)
                                                         else
                                                           player_path(@player)
                                                         end, confirm: "Did you really mean to delete this player?", method: :delete %></div>
<div class="divider"></div>

<%= render 'player_tournaments' %>

<br />

<div class="divider"></div>

<%= render 'player_matches' %>

<%= render 'layouts/new_player' %>