config/routes.rb
Brakkit::Application.routes.draw do

  resources :tournaments do
    member do
      post 'winner'
    end
    collection do
      post 'add_new_tournament'
      get 'search_tournaments'
    end

    resources :players do
      collection do
        post 'multiremove'
        post 'add_new_player'
      end
      member do
        delete 'delete_player_from_tournament_show'
      end
    end
  end

  resources :players do
    collection do
      post 'multiadd'
      post 'add_new_player'
      get 'search_players'
    end
    member do
      put 'update_player_ajax'
    end
  end

  resources :matches do
    collection do
      post 'add_new_match'
      get 'search_matches'
    end
    member do
      post 'verdict'
      post 'add_match_player'
      post 'remove_match_player'
      get 'non_match_players'
      post 'add_player_from_player_picker'
      get 'player_picker_search'
      post 'add_new_player_from_match'
    end

    resources :players do

    end
  end

  root to: 'tournaments#index'

  get '/home',    to: 'tournaments#index'
  get '/contact', to: 'static_pages#contact'
  get '/players', to: 'players#index'
  get '/players/:id', to: 'players#show'
  get '/tournaments/:id', to: 'tournaments#show'
  get '/tournaments/:id/player', to: 'players#show'
  get '/tournaments/:id/players/:id', to: 'players#show'
  post '/players/:id/edit', to: 'players#edit'
  post '/tournaments/:id/players/:id/edit', to: 'players#edit'
  get '/tournaments/:id/start', to: 'tournaments#start_tournament', as: 'start_tournament'
  get '/tournaments/:id/add_index/', to: 'players#add_index', as: 'add_index'
  get '/matches/:id/start_match', to: 'matches#start_match', as: 'start_match'

end

app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :player1_id, :player2_id, :round, :tournament_id, :winner_id, :name

  belongs_to :player1, class_name: Player, foreign_key: :player1_id
  belongs_to :player2, class_name: Player, foreign_key: :player2_id
  belongs_to :winner, class_name: Player, foreign_key: :winner_id

  validates_uniqueness_of :name

  after_commit do |m|
    if(!m.name || m.name.empty?)
      m.name = "Match-#{m.id}"
      m.save
    end

  end

  def players
    players = []
    players << self.player1 if self.player1
    players << self.player2 if self.player2
    players
  end

  private
    def unique_players
      errors.add :players, "The match needs to have two unique players" if self.player1_id == self.player2_id
    end

end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = Match.where(tournament_id: 0).order("created_at DESC").paginate(page: params[:page], per_page: 16)
    @match = Match.new
  end

  def new
    @match = Match.new
  end

  def show
    @match = Match.find(params[:id])
    @player = Player.new
    @count = @match.players.count

    add_breadcrumb "Matches", matches_path
    add_breadcrumb "<span>#{@match.name}</span>", match_path(@match)
  end

  def destroy
    Match.find(params[:id]).destroy
    flash[:success] = "Match deleted!"
    redirect_to matches_path
  end

  def verdict
    @match = Match.find(params['match-id'])
    @player = Player.find(params['player-id'])

    if(@match.player1_id == @player.id)
      @loser = @match.player2
    else
      @loser = @match.player1
    end

    @match.winner = @player
    @player.increment_wins

    @match.save

    respond_to do |format|
      format.json {
         render json: {
             player: @player,
             match: @match,
             winner_name: @player.full_name,
             loser_name: @loser.full_name
         }
      }
    end
  end

  def add_new_match
    @match = Match.new(name: params['name'])

    respond_to do |format|
      format.json {
        if @match.save
          render json: @match
        else
          render json: @match.errors, status: :forbidden
        end
      }
    end
  end

  def search_matches
    search = params['search_term']
    matches = Match.where(tournament_id: 0)

    if !search.empty?
      search_result = matches.where("name LIKE :test", test: "%#{search}%")
    else
      search_result = matches.order("created_at DESC").paginate(page: params[:page], per_page: 16)
    end

    players = Player.select('id, full_name').where('full_name like :test', test: "%#{search}%")
    ids = players.map(&:id)
    search_result = (search_result + matches.find_all_by_player1_id(ids) + matches.find_all_by_player2_id(ids) + matches.find_all_by_winner_id(ids)).uniq

    search_result = search_result.map do |s|
      if s.winner_id != 0
        winner_name = s.winner.full_name
      else
        winner_name = ""
      end

      player1_id = s.player1 ? s.player1_id : 0
      player2_id = s.player2 ? s.player2_id : 0
      player1_name = s.player1 ? Player.find(player1_id).full_name : ""
      player2_name = s.player2 ? Player.find(player2_id).full_name : ""

      {
          id: s.id,
          name: s.name,
          player1_id: player1_id,
          player2_id: player2_id,
          player1_name: player1_name,
          player2_name: player2_name,
          winner_name: winner_name,
          winner_id: s.winner_id
      }
    end

    respond_to do |format|
      format.json {
        render json: {
            search_result: search_result
        }
      }
    end
  end

  def start_match
    @match = Match.find(params[:id])

    add_breadcrumb "Matches", matches_path
    add_breadcrumb "#{@match.name}", match_path(@match)
    add_breadcrumb "<span>Bracket View</span>", start_match_path
  end

  def add_match_player
    @match = Match.find(params['match_id'].to_i)
    player_id = params['player_id'].to_i
    row = 0
    @player = Player.find(player_id)

    if @match.player1_id == 0
      @match.player1_id = player_id
      row = 1
    elsif @match.player2_id == 0
      @match.player2_id = player_id
      row = 2
    end
    @match.save

    respond_to do |format|
      format.json {
        render json: {
          match: @match,
          player: @player,
          row: row
        }
      }
    end
  end

  def remove_match_player
    @match = Match.find(params['match_id'])
    player_id = params['player_id'].to_i
    player = Player.find(player_id)

    if @match.player1_id == player_id
      @match.player1_id = 0
    elsif @match.player2_id == player_id
      @match.player2_id = 0
    end
    @match.save

    respond_to do |format|
      format.json {
        render json: {
            player: player
        }
      }
    end
  end

  def non_match_players

    @match = Match.find(params[:id])
    @non_match_players = Player.where("id NOT IN (?)", [@match.player1_id, @match.player2_id]).order('created_at DESC')

    respond_to do |format|
      format.json{
        render json: {
            players: @non_match_players
        }
      }
    end
  end

  def add_player_from_player_picker
    @match = Match.find(params['match_id'])
    @player = Player.find(params['player_id'])
    row = 0

    if @match.player1_id == 0
      @match.player1_id = params['player_id']
      row = 1
    elsif @match.player2_id == 0
      @match.player2_id = params['player_id']
      row = 2
    end
    @match.save

    respond_to do |format|
      format.json {
        render json: {
            match: @match,
            player: @player,
            row: row,
            player_count: @match.players.count
        }
      }
    end
  end

  def player_picker_search
    @match = Match.find(params['match_id'])
    search = params['search']

    if !search.empty?
      search_result = Player.where("id NOT IN (?)", [@match.player1_id, @match.player2_id]).where("first_name LIKE :search OR last_name LIKE :search OR full_name LIKE :search OR skill LIKE :search", search: "%#{search}%").uniq.reverse
    else
      search_result = Player.where("id NOT IN (?)", [@match.player1_id, @match.player2_id]).order('created_at DESC')
    end

    respond_to do |format|
      format.json {
        render json: {
          search_result: search_result
        }
      }
    end
  end

  def update
    m = Match.find(params['match_id'])
    m.name = params['name']

    respond_to do |format|
      format.json {
        if m.save
          render json: {
              new_name: m.name
          }
        else
          render json: m.errors, status: :forbidden
        end
      }
    end
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_edit_match_name.html.erb
<div class="edit_match_name_class">
    <%= form_for @match, html: { id: 'edit_match_name_form', class: 'nopjax' } do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <ul>
            <li class="match_name_text_field"><%= f.text_field :name, autofocus: true, placeholder: "New Match Name" %></li>
        </ul>
    <% end %>
</div>

app/views/matches/_matches_table.html.erb
<%= will_paginate @matches %>

<table>
    <thead>
    <tr>
        <th>Match</th>
        <th>Player 1</th>
        <th>Player 2</th>
        <th>Winner</th>
    </tr>
    </thead>
        <tbody id="matches_table">
        <% if @matches.any? %>
            <% @matches.each do |m| %>
                    <tr data-match-id="<%= m.id %>">
                        <td><%= link_to m.name, match_path(m) %></td>
                        <td><%= link_to m.player1.full_name, match_player_path(m, m.player1) if m.player1 %></td>
                        <td><%= link_to m.player2.full_name, match_player_path(m, m.player2) if m.player2 %></td>
                        <td><%= link_to m.winner.full_name, match_player_path(m, m.winner) if m.winner %></td>
                    </tr>
            <% end %>
        <% end %>
        </tbody>
</table>

app/views/matches/_new_match.html.erb
<div class="create_form">
    <%= form_for @match, remote: true, html: { id: 'match-dialog-form', class: 'nopjax', title: 'New Match' } do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <ul>
            <li><%= f.text_field :name, autofocus: true, placeholder: "Match Name (Optional)" %></li>
            <li><%= f.submit "Create Match" %></li>
            <li class="cancel_btn" id="match_cancel_btn"><%= button_tag "Cancel", class: "edit_btn" %></li>
        </ul>
    <% end %>
</div>

app/views/matches/index.html.erb
<h2 class="title">Matches</h2>
<div class='btn create_btn nopjax' id='new_match_btn'><%= link_to "New Match", new_match_path %></div>

<%= render 'new_match' %>

<div class="detail">
    <%= pluralize(@matches.count, 'match has', 'matches have') %> been created so far.
</div>
<div class="divider"></div>

<div class="search_box">
    <input type="text" id="match_search" placeholder="Search for match..." class="search">
</div>

<%= render 'matches_table' %>

app/views/matches/show.html.erb
<%= flash[:notice] %>

<%= render 'layouts/breadcrumbs' %>

<h2 class="title"><%= @match.name %></h2>

<% if !@match.winner %>
    <div class="btn start_btn" id="start_match_button">
        <% if @count < 2 %>
            <%= link_to "Start Match", "javascript:void(0);", class: 'nopjax' %>
        <% else %>
            <%= link_to "Start Match", start_match_path(@match), class: 'nopjax' %>
        <% end %>
    </div>
<% else %>
    <div class="btn completed_btn"><%= link_to "Match Completed" %></div>
<% end %>

<div class="btn delete_btn"><%= link_to "Delete Match", @match, confirm: "Did you really mean to delete this match?", method: :delete %></div>

<div class="btn edit_btn" id="edit_match_name_button" data-match-id="<%= @match.id %>"><%= link_to "Edit Match Name" %></div>

<ul class="detail">
    <li><%= pluralize(@count, "player") %></li>
</ul>
<div class="divider"></div>

<h3 class="subtitle">Players</h3>
<div class="btn" id="add_new_player_button" style="<%= 'display: none;' if @count == 2 || @match.winner_id != 0 %>" data-match-id="<%= @match.id %>"> <%= link_to "Add New Player", new_match_player_path(@match) %></div>

<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Skill Level</th>
        <th>Matches Won</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <% player1 = @match.player1 ? @match.player1 : nil %>
    <% player2 = @match.player2 ? @match.player2 : nil %>

    <tr>
        <td>
            <%= link_to player1.full_name, match_player_path(@match, player1) if !player1.nil? %>
        </td>
        <td>
            <%= player1.email if !player1.nil? %>
        </td>
        <td>
            <%= player1.skill if !player1.nil? %>
        </td>
        <td>
            <%= player1.matches_won if !player1.nil? %>
        </td>
        <td>
            <% if @match.winner_id == 0 %>
                <% if !player1.nil? %>
                    <button class="matches_btn matches_remove_btn remove_match_player" data-player-number="1" data-match-id="<%= @match.id %>"
                    data-player-id="<%= @match.player1_id %>">Remove Player</button>
                <% else %>
                    <button class="matches_btn add_match_player" data-player-number="1" data-match-id="<%= @match.id %>">Add Existing Player</button>
                <% end %>
            <% end %>
        </td>
    </tr>
    <tr>
        <td>
            <%= link_to player2.full_name, match_player_path(@match, player2) if !player2.nil? %>
        </td>
        <td>
            <%= player2.email if !player2.nil? %>
        </td>
        <td>
            <%= player2.skill if !player2.nil? %>
        </td>
        <td>
            <%= player2.matches_won if !player2.nil? %>
        </td>
        <td>
            <% if @match.winner_id == 0 %>
                <% if !player2.nil? %>
                    <button class="matches_btn matches_remove_btn remove_match_player" data-player-number="2" data-match-id="<%= @match.id %>"
                    data-player-id="<%= @match.player2_id %>">Remove Player</button>
                <% else %>
                    <button class="matches_btn add_match_player" data-player-number="2" data-match-id="<%= @match.id %>">Add Existing Player</button>
                <% end %>
            <% end %>
        </td>
    </tr>
    </tbody>
</table>

<div id="match_player_picker_wrapper">

    <table id="match_player_picker">
        <thead>
        <th>Name</th>
        <th>Skill</th>
        </thead>

        <tbody id="match_player_picker_body">

        </tbody>

    </table>
</div>

<%= render "layouts/new_player" %>

<%= render "edit_match_name" %>

app/views/matches/start_match.html.erb
<%= flash[:notice] %>

<%= render 'layouts/breadcrumbs' %>

<h2 class="title"><%= @match.name %></h2><br />

<ul class="detail">
    <li id="match-winner">
        <% winner = @match.winner %>
        <% if winner %>
            Winner: <a href="/players/<%= winner.id %>"><%= winner.full_name %></a>
        <% else %>
            There is no winner yet.
        <% end %>
    </li>
</ul>

<div class="divider"></div>


<div class="matches-row">
    <ul class="matches-list">
        <div id="match-<%= @match.id %>" class="match">
            <% winner_id = @match.winner_id %>

            <% p1 = @match.player1 if @match.player1_id != 0 %>
            <% p2 = @match.player2 if @match.player2_id != 0 %>

            <% if p1 && p2 && winner_id != 0 %>

                <% if winner_id == p1.id %>
                    <% p1_is_winner = true %>
                <% else %>
                    <% p2_is_winner = true %>
                <% end %>
            <% end %>


            <li class="<% if winner_id != 0 %>
                                    <%= p1_is_winner ? "match-winner" : "match-loser" %>
                               <% end %>">
                <% if winner_id != 0 %>
                    <%= gravatar_for p1, size: 30 %>
                    <%= p1 ? "#{p1.first_name} #{p1.last_name}" : ""  %>
                <% end %>
                <% if winner_id == 0 && p1 %>
                    <button class="winner_btn match_winner_btn" data-match-id="<%= @match.id %>" data-player-id="<%= p1.id if p1%>" data-round-id="<%= @match.round %>"
                            data-player-number="1"><%= gravatar_for p1, size: 30 %><%= p1 ? "#{p1.first_name} #{p1.last_name}" : ""  %></button></li>
                <% end %>
                <li class="<% if winner_id != 0 %>
                                    <%= p2_is_winner ? "match-winner" : "match-loser" %>
                               <% end %>">
                    <% if winner_id != 0 %>
                        <%= gravatar_for p2, size: 30 %>
                        <%= p2 ? "#{p2.first_name} #{p2.last_name}" : ""  %>
                    <% end %>
                    <% if winner_id == 0 && p2 %>
                        <button class="winner_btn match_winner_btn" data-match-id="<%= @match.id %>" data-player-id="<%= p2.id if p2%>" data-round-id="<%= @match.round %>"
                                data-player-number="2"><%= gravatar_for p2, size: 30 %><%= p2 ? "#{p2.first_name} #{p2.last_name}" : ""  %></button></li>
                    <% end %>
                    <!--
                    <li>Round <%= @match.round %></li>

                    <% if winner_id != 0 %>
                        <% winner = @match.winner %>
                    <% end %>
                    <li>Winner: <%= "#{winner.first_name} #{winner.last_name}" if winner %></li>
                    <br />
                    -->

                    </div>
    </ul>
</div>