config/routes.rb
Brakkit::Application.routes.draw do

  resources :tournaments do
    member do
      post 'winner'
    end
    collection do
      post 'add_new_tournament'
      get 'search_tournaments'
    end

    resources :players do
      collection do
        post 'multiremove'
        post 'add_new_player'
      end
      member do
        delete 'delete_player_from_tournament_show'
      end
    end
  end

  resources :players do
    collection do
      post 'multiadd'
      post 'add_new_player'
      get 'search_players'
    end
    member do
      put 'update_player_ajax'
    end
  end

  resources :matches do
    collection do
      post 'add_new_match'
      get 'search_matches'
    end
    member do
      post 'verdict'
      post 'add_match_player'
      post 'remove_match_player'
      get 'non_match_players'
      post 'add_player_from_player_picker'
      get 'player_picker_search'
      post 'add_new_player_from_match'
    end

    resources :players do

    end
  end

  root to: 'tournaments#index'

  get '/home',    to: 'tournaments#index'
  get '/contact', to: 'static_pages#contact'
  get '/players', to: 'players#index'
  get '/players/:id', to: 'players#show'
  get '/tournaments/:id', to: 'tournaments#show'
  get '/tournaments/:id/player', to: 'players#show'
  get '/tournaments/:id/players/:id', to: 'players#show'
  post '/players/:id/edit', to: 'players#edit'
  post '/tournaments/:id/players/:id/edit', to: 'players#edit'
  get '/tournaments/:id/start', to: 'tournaments#start_tournament', as: 'start_tournament'
  get '/tournaments/:id/add_index/', to: 'players#add_index', as: 'add_index'
  get '/matches/:id/start_match', to: 'matches#start_match', as: 'start_match'

end

app/views/layouts/_breadcrumbs.html.erb
<nav class="breadcrumbs">
    <%= render_breadcrumbs :separator => '' %>
</nav>
<div class="clear"></div>

app/views/layouts/_footer.html.erb
<footer>
    &copy; Elijah Cooper, Inder Dhir
</footer>

app/views/layouts/_header.html.erb
<div id="nav-bar-back">	
	<nav class="main_nav">
	    <ul>
	    	<li id="logo">Social Bracket</li>
	        <li id="contact-button"><%= link_to "Contact", contact_path %></li>
	        <li id="players_header"><%= link_to "Players", players_path %></li>
	        <li><%= link_to "Matches", matches_path %></li>
	        <li><%= link_to "Tournaments", tournaments_path %></li>
	    </ul>
	</nav>
</div>

app/views/layouts/_new_player.html.erb
<div class="create_form_player">
    <%= form_for @player, remote: true, html: { id: 'player-dialog-form', class: 'nopjax', title: 'New ' } do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <ul>
            <li><span>First Name</span></li>
            <li><%= f.text_field :first_name, autofocus: true %></li>
            <li><span>Last Name</span></li>
            <li><%= f.text_field :last_name %></li>
            <li><span>Email Address</span></li>
            <li><%= f.email_field :email %></li>
            <li><span>Skill Level</span></li>
            <li><%= f.select :skill, 1..10 %></li>

            <% if @tournament %>
                <%= f.hidden_field :tournament_id, value: @tournament.id %>
            <% end %>

        </ul>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <link href='http://fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>
    <title id='page_title'>Oracle Social Bracket</title>
    <%= stylesheet_link_tag  "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
</head>
<body>
<%= render "layouts/header" %>
<div id="ajax_spinner"><%= image_tag('ajax-loader.gif') %></div>

<div id="container" class="wrapper">
    <% flash.each do |key, value| %>
	        <div class="alert alert-<%= key %>"><%= value %></div>
	    <% end %>
		<%= yield %>
	<!-- keep this padding div -->
	<div id="footer-padding"></div> 
</div>
<%= render "layouts/footer" %>
</body>
</html>